# Generated by Django 4.1.7 on 2023-03-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0002_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='paymenttype',
            field=models.CharField(max_length=100),
        ),
    ]
