# Generated by Django 4.1.7 on 2023-03-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0003_alter_purchase_paymenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='vendorid',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
